on:
  pull_request:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test MarkBind PR Preview Action
    steps:
      - uses: actions/checkout@v2
      - id: markbind-pr-preview
        uses: ./
        with:
          baseUrl: 'tlylt'
          token: ${{ secrets.SURGE_TOKEN }}